Resolve CRUD-for-review#74
chingu-voyages/v33-bears-team-15be pull request #15
Opened 2021-10-07 13:58 UTC by ArturoGrullon

### CRUD operations

Integrated the bases for the CRUD operations, yet I had ambiguities I commented out in the code.

- Users cannot review their own books?
- Users can only review once?

> More details in the codebase

2021-10-07 16:08 UTC, Kerosz requested changes
Left some suggestions, I did not test the code nor I pulled down the branch, I just looked through the code in the commit.

2021-10-07 16:08 UTC, Kerosz commented on src/review/dto/create-review.dto.ts
> +  @MinLength(100, { message: "Name must have at least 100 characters!" })
```suggestion
  @MinLength(100, { message: "Comment must have at least 100 characters!" })
```

2021-10-07 16:08 UTC, Kerosz commented on src/review/models/review.entity.ts
> +  @Prop({ required: true, unique: true, trim: true, minlength: 54, maxlength: 4096 })
We don't need `unique` here, also the min length in the validator is bigger than the one mongo can store, which will yield an error.

2021-10-07 16:08 UTC, Kerosz commented on src/review/review.service.ts
> +    if (reviewRecord.user !== userId) throw new NotFoundException("Incorrect user");
We could use a `UnauthorizedException` here instead of a `NotFound`. THis might be an issue also, because `users` can mark any review as helpful, even if it's not their own, but in the same time, they cannot modify any other fields of the review except `helpful` if it's not their own. So we need to find a way, probably some if checks to make sure of that

2021-10-07 16:08 UTC, Kerosz commented on src/review/review.service.ts
> +      throw new NotFoundException("This review doesn't belong to you!");
Same as above we can use a `UnauthorizedException`

2021-10-07 16:08 UTC, Kerosz commented on src/review/role.enum.ts
> +export enum Role {
I was looking at the other `Role` enum we have in the `auth` directory, and it seems that enum has the Reader and the Critic roles in there, and those are the ones we need. You can just use that one.

`src/auth/role.enum.ts` whenever you need this

2021-10-07 16:08 UTC, Kerosz commented on src/review/dto/update-review.dto.ts
> +  countHelpful?: string;
This value, will only be changed on the BE side, the frontend doesn't need to directly modify this value, as it only stands as a counter, everytime we add a new ID into the `helpful` array, we increment this `countHelpful` as well

2021-10-07 16:08 UTC, Kerosz commented on src/review/models/review.entity.ts
> +  @Prop({ required: true })
we could default this to 0

2021-10-07 16:08 UTC, Kerosz commented on src/review/dto/create-review.dto.ts
> +  user?: string;
We don't need this field in here, we'll get the user ID from the controller params

2021-10-07 16:08 UTC, Kerosz commented on src/review/dto/create-review.dto.ts
> +  userType?: string;
we probably don't want this here also, as we don't trust the FE to tell us what kind of type the review is, we'll check this on our own based on the userId we get from the controller. ( making a request to get the user data based on their ID and check what role they have )

2021-10-07 16:08 UTC, Kerosz commented on src/review/review.service.ts
> +  async create(_userId: string, _bookId: string, r: CreateReviewDto) {
we are going to use this userId from here in order to create the review `user` field, instead of getting the userId from the review body.

after we create the review we need to make a request to update the book by the `bookId` and add the review id we just created to the `reviews` array field of that book, as well as incrementing the `totalReviews` on that book record

2021-10-07 17:23 UTC, ArturoGrullon commented on src/review/models/review.entity.ts
> +  @Prop({ required: true, unique: true, trim: true, minlength: 54, maxlength: 4096 })
I don't follow, isn't the validator set to enter a string with at least 54 characters? how come this would yield an error

2021-10-07 17:30 UTC, ArturoGrullon commented on src/review/dto/update-review.dto.ts
> +  countHelpful?: string;
Yeah, you are right

2021-10-07 17:33 UTC, ArturoGrullon commented on src/review/dto/create-review.dto.ts
> +  user?: string;
Hmm, that's true 🤔

2021-10-07 17:35 UTC, ArturoGrullon commented on src/review/dto/create-review.dto.ts
> +  userType?: string;
Got it

2021-10-07 18:30 UTC, ArturoGrullon commented on src/review/review.service.ts
> +  async create(_userId: string, _bookId: string, r: CreateReviewDto) {
Got it, I used this approach: 

`const newTotalReview = await this.bookRepository.findById(_bookId);
    let counter = newTotalReview?.totalReviews || 0;

    await this.bookRepository.findByIdAndUpdate(_bookId, {
      totalReviews: counter++,
    });`

Do you have a better one?

2021-10-07 19:10 UTC, Kerosz commented on src/review/models/review.entity.ts
> +  @Prop({ required: true, unique: true, trim: true, minlength: 54, maxlength: 4096 })
Hmm now that I think about it you are right, it won't give errors, but still, make it to have same values, I think it was 100

2021-10-07 19:26 UTC, Kerosz commented on src/review/review.service.ts
> +  async create(_userId: string, _bookId: string, r: CreateReviewDto) {
Probably add a check on it:

```ts
const bookRecord = await this.bookRepository.findById(bookId);

if(!bookRecord) throw new NotFoundError("The book you are trying to add the review for doesn't exist"!);

await this.bookRepository.findByIdAndUpdate(bookId, {
  totalReviews: bookRecord.totalReviews++,
  reviews: [...bookRecord.reviews, reviewRecord._id],
});
```

The code above, it's probable and it's a suggestion, I did only write this here in the github comments and did not test it

Was there a reason why we had to do `|| 0` before ? I did check the book service for creating the book and it seems that we default the `totalReviews` field to 0;

![image](https://user-images.githubusercontent.com/31253154/136449579-16cc6358-c521-4916-957b-4089f3491161.png)

2021-10-07 20:10 UTC, ArturoGrullon commented on src/review/review.service.ts
> +  async create(_userId: string, _bookId: string, r: CreateReviewDto) {
I was trying something very similar to what you send me but I was getting an error... 

I notice that `if(!bookRecord) throw new NotFoundError("The book you are trying to add the review for doesn't exist"!);` avoids that error 😄

That was the reason behind the 0.

2021-10-07 20:10 UTC, ArturoGrullon commented on src/review/models/review.entity.ts
> +  @Prop({ required: true, unique: true, trim: true, minlength: 54, maxlength: 4096 })
Got it

2021-10-08 08:08 UTC, Kerosz requested changes

2021-10-08 08:08 UTC, Kerosz commented on src/review/models/review.entity.ts
> +  @Prop({ required: true, type: SchemaTypes.ObjectId, default: 0 })
I ment to default the `countHelpful` to 0, I'm not sure if I said helpful or not, but `countHelpful` is what I ment :D

2021-10-08 08:08 UTC, Kerosz commented on src/review/review.service.ts
>        deleted: await this.reviewRepository.deleteOne({ _id: reviewId }),
In here we kind of need to do what we did in create, I forgot about this last night. What I mean is when we delete a review, we should delete the review id from the `book.reviews` and we should decrement the `book.totalReviews` count

2021-10-08 08:08 UTC, Kerosz commented on src/review/review.service.ts
>        helpful: updateReviewDto.helpful || reviewRecord.helpful,
In here we should also increment the `countHelpful`. So `reviewRecord.countHelpful++` If the user updated the `helpful` field

2021-10-08 08:08 UTC, Kerosz commented on src/review/review.service.ts
> +  async create(_userId: string, bookId: string, r: CreateReviewDto) {
We should also not use the underscore for the `userId`. Underscore prefix kind of means the variable is not used or it shouldn't be changed, but we are using it

2021-10-08 12:55 UTC, ArturoGrullon commented on src/review/models/review.entity.ts
> +  @Prop({ required: true, type: SchemaTypes.ObjectId, default: 0 })
Hehe, my bad

2021-10-08 13:13 UTC, ArturoGrullon commented on src/review/review.service.ts
>        helpful: updateReviewDto.helpful || reviewRecord.helpful,
I'm guessing this is gonna be dynamic, like if the user changes its mind and says:
- "You know what?"
- "This review actually sucks!"

I haven't seen the frontend UI but I guess if the person clicks again the button it can delete his/her like.

Btw, are review owners gonna be able to edit their review?

2021-10-08 13:14 UTC, ArturoGrullon commented on src/review/review.service.ts
>        deleted: await this.reviewRepository.deleteOne({ _id: reviewId }),
Yeah, you are right. 

Totally miss that, thanks for pointing it out.

2021-10-08 14:03 UTC, ArturoGrullon commented on src/review/review.service.ts
>        helpful: updateReviewDto.helpful || reviewRecord.helpful,
After some thinking I was mixing the endpoints, I created that one in the first place for the creators of the reviews to edit their reviews (which I still don't know if they are gonna be able to). 

I created another end-point for handling the helpulf stuff we talk about, here it's:
```ts
async updateHelpful(userId: string, reviewId: string) {
    const reviewRecord = await this.reviewRepository.findById(reviewId);
    if (!reviewRecord) throw new NotFoundException("No review record found!");
    //Todo?: Users need to be authenticated to be able to vote

    if (reviewRecord.helpful.find((id) => id === userId)) {
      const filteredArray = reviewRecord.helpful.filter((id) => id !== userId);
      return await this.reviewRepository.findByIdAndUpdate(reviewId, {
        helpful: filteredArray,
        countHelpFul: reviewRecord.countHelpFul--,
      });
    }

    return await this.reviewRepository.findByIdAndUpdate(reviewId, {
      helpful: [...reviewRecord.helpful, userId],
      countHelpFul: reviewRecord.countHelpFul++,
    });
  }```

2021-10-08 14:11 UTC, ArturoGrullon commented on src/review/review.service.ts
>        deleted: await this.reviewRepository.deleteOne({ _id: reviewId }),
I think it would have been nice that the reviews hold a reference to their books, so we would just run a query and won't be manually going up and down any time we create or delete a review.

2021-10-08 14:14 UTC, ArturoGrullon commented on src/review/review.service.ts
>        deleted: await this.reviewRepository.deleteOne({ _id: reviewId }),
Come to think of it... we could run a query to know the helpful count as well inside the reviews

2021-10-08 15:49 UTC, Kerosz requested changes

2021-10-08 15:49 UTC, Kerosz commented on src/review/review.service.ts
> +    //Todo?: Users need to be authenticated to count as helpful
Assuming you are using the JWT guard on the controller for all the review routes, then it means the user cannot perform that action if they aren't logged in, and pretty much all review routes need to be guarded

2021-10-08 15:49 UTC, Kerosz commented on src/review/review.controller.ts
> +export class ReviewController {
All endpoints of the controller needs to be guarded with a JwtGuard: ` @UseGuards(JwtAuthGuard)`

We should also implement another endpoint that gets all the review by a book id, something like:

`@Get(":bookId")`

and add another function on the service that returns all the reviews from that book, which should only have the jwt guard and will probably be the endpoint we use to get all the reviews for a book when we go to that book details page

2021-10-08 15:49 UTC, Kerosz commented on src/review/review.controller.ts
> +  findAll() {
Getting all the reviews from the DB would require an admin or super admin role:

`@UseRoles(Role.ADMIN, Role.SUPER_ADMIN)`

don't forget to add the `RolesGuard` to the use guards decorator

2021-10-08 16:37 UTC, ArturoGrullon commented on src/review/review.service.ts
> +    //Todo?: Users need to be authenticated to count as helpful
Oh, so that's what the JWT guard doing 😄.

2021-10-08 16:39 UTC, ArturoGrullon commented on src/review/review.controller.ts
> +export class ReviewController {
Got it, totally miss it. 

Hehe, still connecting the dots here. I will be adding the guard at the controller

2021-10-08 16:42 UTC, ArturoGrullon commented on src/review/review.controller.ts
> +  findAll() {
Right away

2021-10-08 16:56 UTC, Kerosz requested changes
Can we also get Swagger Api Docs for the controller ?

![image](https://user-images.githubusercontent.com/31253154/136594774-23e4be41-245c-49c8-bc82-9561819caaec.png)

2021-10-08 16:56 UTC, Kerosz commented on src/review/review.controller.ts
> +@UseGuards(JwtAuthGuard)
You forgot to use the `RolesGuard`

2021-10-08 17:37 UTC, ArturoGrullon commented on src/review/review.controller.ts
> +@UseGuards(JwtAuthGuard)
Hehe, I always miss something

2021-10-08 17:51 UTC, Kerosz approved these changes
I did not test this directly, code looks good, so I would assume it's working as intended

2021-10-08 17:59 UTC, merged